# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "yunion.io/x/log"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/pkg"

[[override]]
    name = "k8s.io/helm"
    version = "v2.12.3"

[[override]]
    name = "k8s.io/cli-runtime"
    version = "kubernetes-1.12.0"

[[override]]
    name = "k8s.io/api"
    version = "kubernetes-1.13.0"

[[override]]
    name = "k8s.io/apimachinery"
    version = "kubernetes-1.13.0"

[[override]]
    name = "k8s.io/client-go"
    version = "kubernetes-1.13.0"

[[override]]
    name = "k8s.io/kubernetes"
    branch = "release-1.13"
    #version = "v1.12.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/apiserver"
  #revision = "cf5eff4f5e8f6019796cb18c69918b9f2f09e6db"
  #revision = "b6aa1175dafa586b8042c7bfdcd1585f9ecfaa08"
  branch = "release-1.13"

[[override]]
    name = "github.com/ugorji/go"
    revision = "f3cacc17c85ecb7f1b6a9e373ee85d1480919868"

[[override]]
    name = "github.com/russross/blackfriday"
    version = "=v1.5.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
    name = "github.com/docker/docker"
    revision = "ecf4125b85e0faa57d2739348e0d453c1d24d10c"

[[override]]
    name = "github.com/docker/distribution"
    revision = "3800056b8832cf6075e78b282ac010131d8687bc"

[[override]]
    name = "github.com/docker/go-connections"
    revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"

[[constraint]]
    name = "yunion.io/x/yke"
    branch = "release/2.4.0"

[[constraint]]
    name = "yunion.io/x/onecloud"
    branch = "release/2.6.0"

[[constraint]]
    name = "yunion.io/x/cluster-api-provider-onecloud"
    branch = "master"

[[constraint]]
    name = "google.golang.org/grpc"
    version = "1.11.3"
