#!/bin/bash

export YUNION_KUBE_TOKEN="e984c7bc-035b-4cd8-8309-f03f4823f99b"
export YUNION_KUBE_SERVER="https://10.168.222.183:8443"
export YUNION_KUBE_NODE_ID="fake-node01"

BIN_DIR=$(dirname $(dirname $(readlink -f "$BASH_SOURCE")))

$BIN_DIR/bin/kube-agent -d --server $YUNION_KUBE_SERVER --token $YUNION_KUBE_TOKEN --id $YUNION_KUBE_NODE_ID
